version: '3.8'

services:
  app:
    build: ./
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - app_data:/app/data

  prometheus:
    image: prom/prometheus
    volumes:
      - ./ops/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  app_data:
  prometheus_data:
  grafana_data:
