name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run bootstrap
        run: ./bootstrap.sh
      - name: Run tests
        run: |
          source .venv/bin/activate
          python -m pytest -v
      - name: Build Docker image
        run: docker build .
      - name: Setup Docker Compose
        uses: docker/setup-compose-action@v1
      - name: Start services
        run: docker compose up -d
      - name: Stop services
        if: always()
        run: docker compose down
